### ISSUE TITLE
Deprecate positional arguments in Plugin __init__

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#155]
@nickhand I just realized this backtrace is totally uncomprehensible. Looks like if we disable positional arguments in Plugin __init__, then at least we can print out what keywords are expected and what keywords are provided.

```

    main()
  File "/dev/shm/local/bin/nbkit.py", line 100, in main
    params, extra = Algorithm.parse_known_yaml(alg_name, stream)
  File "/dev/shm/local/lib/python2.7/site-packages/nbodykit/extensionpoints.py", line 544, in parse_known_yaml
    return ReadConfigFile(stream, klass.schema)
  File "/dev/shm/local/lib/python2.7/site-packages/nbodykit/utils/config.py", line 104, in ReadConfigFile
    fill_namespace(ns, schema[name], extra, missing)
  File "/dev/shm/local/lib/python2.7/site-packages/nbodykit/utils/config.py", line 50, in fill_namespace
    fill_namespace(subns, arg[k], subconfig, missing)
  File "/dev/shm/local/lib/python2.7/site-packages/nbodykit/utils/config.py", line 41, in fill_namespace
    raise ConfigurationError("unable to cast '%s' value: %s" %(arg.name, str(e)))
nbodykit.utils.config.ConfigurationError: unable to cast 'field.DataSource' value: failure to parse plugin:

Traceback (most recent call last):
  File "/dev/shm/local/lib/python2.7/site-packages/nbodykit/extensionpoints.py", line 208, in from_config
    return cls.create(plugin_name, use_schema=True, **kwargs)
  File "/dev/shm/local/lib/python2.7/site-packages/nbodykit/extensionpoints.py", line 175, in create
    toret = klass(**kwargs)
  File "/dev/shm/local/lib/python2.7/site-packages/nbodykit/utils/config.py", line 369, in wrapper
    raise TypeError(msg)
TypeError: error initializing __init__ for 'FOFDataSource':

Traceback (most recent call last):
  File "/dev/shm/local/lib/python2.7/site-packages/nbodykit/utils/config.py", line 363, in wrapper
    return init(self, *args, **kwargs)
TypeError: __init__() takes at least 3 arguments (4 given)

```

**Comment by nickhand** [comment]
yeah, I was using this mechanism mostly for debugging purposes and then forgot to implement something more readable. I don't think we necessarily need to deprecate positional arguments though, right? The schema in theory knows what parameters it needs, so we could do something fancier and print out the extra/missing arguments here

**Comment by rainwoodman** [comment]
But what are positional arguments good for in this case?

**Comment by nickhand** [comment]
I think the main utility is that the schema automatically knows that positional arguments are required and the keywords are optional. If they are all keywords, then the user has to specifically set `required = True` in the schema.
