### ISSUE TITLE
nbkit-batch failure.

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#253]
```
[ 000000.16 ]  46:nid00009 10-18 14:35  TaskManager     ERROR    Traceback (most recent call last):
  File "/dev/shm/local/lib/python3.5/site-packages/nbodykit/utils/taskmanager.py", line 275, in compute
    self.wait()
  File "/dev/shm/local/lib/python3.5/site-packages/nbodykit/utils/taskmanager.py", line 195, in wait
    result = self.function(*args)
  File "/dev/shm/local/bin/nbkit-batch.py", line 368, in compute_one_task
    params, extra = ReadConfigFile(open(this_config, 'r').read(), self.algorithm_class.schema)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpsec297zt'
```

Looks like on new Edison /tmp is local to the computing node.

**Comment by nickhand** [comment]
Interesting...the name of the temporary config file is being created by the ``tempfile`` package. It shouldn't create a file that then doesn't exist, no?

**Comment by rainwoodman** [comment]
It exists on one node but not on another.

Yu

**Comment by nickhand** [comment]
Yep that makes sense. I'll take a look at a fix
