### ISSUE TITLE
problem with SurveyDataPairCount

### ISSUE THREAD

**Issue by Moctobers** [bccp/nbodykit#508]
Hi,

I try to do pair counts using the function **SurveyDataPairCount**, 

> pair_table = SurveyDataPairCount('2d', first = data, edges=[1,3], cosmo = cosmo,redshift='Z')

then I receive the following error message,

> RuntimeError: calling the function 'Corrfunc.mocks.DDsmu_mocks.DDsmu_mocks' failed, likely due to issues with input data/parameters. Open at issue at https://github.com/bccp/nbodykit/issues for further help.
exception: Could not import the C extension for the on-skypair counter.
stdout: 
stderr:

**Comment by Moctobers** [comment]
my original question was to follow the example **boss-dr12-data.ipynb** and extend the power spectrum for joint ngc and sgc.
Does this function already exist?

thank you again!

**Comment by rainwoodman** [comment]
Looks like your installation is broken. Was this from conda or did you pip install by yourself?

```Could not import the C extension for the on-skypair counter.```

**Comment by Moctobers** [comment]
Hi !

I installed via conda. 

p.s. The other modules all work fine and I can follow the complete example in **boss-dr12-data.ipynb**

**Comment by rainwoodman** [comment]
FKP and SurveyDataPairCount use different backends. 

What do you get if you copy and run the test `test_survey_auto` of algorithms/pair_counters/tests/test_2d.py ? (some slight fiddling may be needed.

What operating system do you use?

**Comment by rainwoodman** [comment]
Are you using Python 2 or 3? Is there a full stack trace of the error?

**Comment by nickhand** [comment]
This could be related to the change to the upstream version of the corrfunc
repo from my fork if the API changed at all before being merged in.

**Comment by rainwoodman** [comment]
The tests passed, so it is unlikely due to this.

**Comment by Moctobers** [comment]
I am using macOS High Sierra version 10.13.5.

The full output for running **test_survey_auto(1)** is:

`[ 000068.31 ]   0: 07-07 11:28  SurveyDataPairCount INFO     using cpu grid decomposition: (1, 1, 1)
[ 000068.32 ]   0: 07-07 11:28  SurveyDataPairCount INFO     position variable range on rank 0 (max, min) = [-134.35415308 1678.89952173 1682.52462445], [-1786.78335158 -1599.91050052   -88.34199628]
[ 000068.33 ]   0: 07-07 11:28  SurveyDataPairCount INFO     Load balance done
[ 000068.34 ]   0: 07-07 11:28  SurveyDataPairCount INFO     correlating 1000 x 1000 objects in total
[ 000068.34 ]   0: 07-07 11:28  SurveyDataPairCount INFO     correlating A x B = 1000 x 1000 objects (median) per rank
[ 000068.34 ]   0: 07-07 11:28  SurveyDataPairCount INFO     min A load per rank = 1000
[ 000068.34 ]   0: 07-07 11:28  SurveyDataPairCount INFO     max A load per rank = 1000
[ 000068.34 ]   0: 07-07 11:28  SurveyDataPairCount INFO     (even distribution would result in 1000 x 1000)
[ 000068.42 ]   0: 07-07 11:28  MPICorrfuncCallable INFO     calling function 'Corrfunc.mocks.DDsmu_mocks.DDsmu_mocks'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mianoctobers/.conda/envs/nbodykit-env/lib/python2.7/site-packages/runtests/mpi/tester.py", line 90, in wrapped
    rt = func(*args, comm=comm)
  File "test_2d.py", line 173, in test_survey_auto
    r = SurveyDataPairCount('2d', source, redges, cosmo, weight='Weight', Nmu=Nmu)
  File "/Users/mianoctobers/.conda/envs/nbodykit-env/lib/python2.7/site-packages/nbodykit/algorithms/pair_counters/mocksurvey.py", line 122, in __init__
    self.run()
  File "/Users/mianoctobers/.conda/envs/nbodykit-env/lib/python2.7/site-packages/nbodykit/algorithms/pair_counters/mocksurvey.py", line 185, in run
    self.pairs = func(pos1, w1, pos2, w2, **attrs['config'])
  File "/Users/mianoctobers/.conda/envs/nbodykit-env/lib/python2.7/site-packages/nbodykit/algorithms/pair_counters/corrfunc/mocks.py", line 75, in __call__
    return CorrfuncMocksCallable.__call__(self, pos1, w1, pos2, w2, **config)
  File "/Users/mianoctobers/.conda/envs/nbodykit-env/lib/python2.7/site-packages/nbodykit/algorithms/pair_counters/corrfunc/mocks.py", line 52, in __call__
    return MPICorrfuncCallable.__call__(self, sizes, kws, callback=callback)
  File "/Users/mianoctobers/.conda/envs/nbodykit-env/lib/python2.7/site-packages/nbodykit/algorithms/pair_counters/corrfunc/base.py", line 148, in __call__
    this_pc = run(chunk)
  File "/Users/mianoctobers/.conda/envs/nbodykit-env/lib/python2.7/site-packages/nbodykit/algorithms/pair_counters/corrfunc/base.py", line 134, in run
    return self._run(self.callable, kwargs)
  File "/Users/mianoctobers/.conda/envs/nbodykit-env/lib/python2.7/site-packages/nbodykit/algorithms/pair_counters/corrfunc/base.py", line 220, in _run
    raise RuntimeError(msg)
RuntimeError: calling the function 'Corrfunc.mocks.DDsmu_mocks.DDsmu_mocks' failed, likely due to issues with input data/parameters. Open at issue at https://github.com/bccp/nbodykit/issues for further help.
exception: Could not import the C extension for the on-skypair counter.
stdout: 
stderr: 
`

**Comment by rainwoodman** [comment]
Thanks. This is likely a problem with the compiled corrfunc binary -- it is built with XCode 6.4, and ended up incompatible with your version of OSX.  

Could you also show me the output of
```
ldd /Users/mianoctobers/.conda/envs/nbodykit-env/lib/python2.7/site-packages/Corrfunc/*.so
```

And if there is objdump on OSX, it will be helpful if I can look at the output of
```
objdump -T /Users/mianoctobers/.conda/envs/nbodykit-env/lib/python2.7/site-packages/Corrfunc/*.so
```

What's your output of
```
conda list corrfunc
```

If it says 2.1.0rc1, then see if reverting to an older version works:

```
conda install corrfunc=2.0
```

Another possible way to get around this is to locally install corrfunc (and it will replace the one you currently have):

```
pip install -U --no-deps -I --no-cache corrfunc
```

**Comment by rainwoodman** [comment]
@ybh0822 Could you see if you can reproduce this error?

**Comment by Moctobers** [comment]
Hi,

thanks!

I don't have objdump installed, but I guess otool does the similar thing on mac (?) 
the output for *otool -L /Users/mianoctobers/.conda/envs/nbodykit-env/lib/python2.7/site-packages/Corrfunc/*.so * is:

> /Users/mianoctobers/.conda/envs/nbodykit-env/lib/python2.7/site-packages/Corrfunc/_countpairs.so:
	@rpath/python2.7/site-packages/Corrfunc/_countpairs.so (compatibility version 2.0.0, current version 2.0.1)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	@rpath/libgsl.23.dylib (compatibility version 24.0.0, current version 24.0.0)
	@rpath/libgslcblas.0.dylib (compatibility version 1.0.0, current version 1.0.0)
/Users/mianoctobers/.conda/envs/nbodykit-env/lib/python2.7/site-packages/Corrfunc/_countpairs_mocks.so:
	@rpath/python2.7/site-packages/Corrfunc/_countpairs_mocks.so (compatibility version 2.0.0, current version 2.0.1)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	@rpath/libgsl.23.dylib (compatibility version 24.0.0, current version 24.0.0)
	@rpath/libgslcblas.0.dylib (compatibility version 1.0.0, current version 1.0.0)

the output for *conda list corrfunc* is:

> # packages in environment at /Users/mianoctobers/.conda/envs/nbodykit-env:
> #
> # Name                    Version                   Build  Channel
> corrfunc                  2.0.0            py27h917ab60_4    bccp

**Comment by rainwoodman** [comment]
That's not good. You are using the older version already!

What do you get with
```
import Corrfunc._countpairs
```
or

```
import Corrfunc._countpairs_mocks
```

**Comment by Moctobers** [comment]
both the commands report image not found:

>  import Corrfunc._countpairs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/mianoctobers/.conda/envs/nbodykit-env/lib/python2.7/site-packages/Corrfunc/_countpairs.so, 2): Library not loaded: @rpath/libgsl.23.dylib
  Referenced from: /Users/mianoctobers/.conda/envs/nbodykit-env/lib/python2.7/site-packages/Corrfunc/_countpairs.so
  Reason: image not found


> import Corrfunc._countpairs_mocks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/mianoctobers/.conda/envs/nbodykit-env/lib/python2.7/site-packages/Corrfunc/_countpairs_mocks.so, 2): Library not loaded: @rpath/libgsl.23.dylib
  Referenced from: /Users/mianoctobers/.conda/envs/nbodykit-env/lib/python2.7/site-packages/Corrfunc/_countpairs_mocks.so
  Reason: image not found

**Comment by rainwoodman** [comment]
This is interesting: otool found libgsl.23.dylib but the loader couldn't. 
Can you search for libgsl.23.dylib with `find` and show me the result?

**Comment by Moctobers** [comment]
emm, find returns nothing:

> find ~/ -name 'libgsl.23.dylib'

**Comment by rainwoodman** [comment]
``` conda list gsl```

If nothing shows up, then probably installing gsl would fix it:

```
conda install gsl
```

**Comment by Moctobers** [comment]
i have gsl installed both in/outside of the nbodykit environment:

> # Name                    Version                   Build  Channel
gsl                       1.16                          2    NLeSC

however, **find ~/ -name 'libgsl.23.dylib'** and **import Corrfunc._countpairs** return the same message as before

**Comment by rainwoodman** [comment]
Try to install gsl=2.4 This is why. Corrfunc was built against gsl=2.4, and somehow your gsl has been pinned to 1.6, causing the symbol to be missing. We will need to pin gsl in the conda recipe.

**Comment by Moctobers** [comment]
perfect, it works now! thanks!
