### ISSUE TITLE
Problems running SimulationBox3PCF at NERSC

### ISSUE THREAD

**Issue by mmarianav** [bccp/nbodykit#590]
**Describe the bug**

**Steps To Reproduce**
It helps us to diagnose the problem if you can describe the steps to reproduce the behaviour. 

**Actual behaviour**
What happens when you perform the steps to reproduce

**Expected behaviour**
What would you expected to happen. Can be as simple as 'this should work', if the expectation is obvious; but free free to elaborate if the situation is complicated.

**Screenshots**
If applicable, add screenshots to illustrate your problem.
For example, this can be a screenshot of the relevant sections of your notebook.

**Version**
Find the version of nbodykit by running
```
import nbodykit; print(nbodykit, nbodykit.__version__);
```
If you suspect the problem is related to a dependency (e.g. Corrfunc, pmesh, or mcfit), then it is useful to report the version of that dependency as well (replacing `nbodykit` with the package name).

**Additional context**
Provide any additional context about the problem here.

**Comment by mmarianav** [comment]
Hello
I am trying to run SimualtionBox3PCF with many nodes, using the following job

# load nbodykit
source /usr/common/contrib/bccp/conda-activate.sh 3.6

# run the main nbodykit example
srun -n 16 python 3pcf_example.py

And I got the following error
Ylm expressions...
Traceback (most recent call last):
  File "3pcf_example.py", line 15, in <module>
    result = SimulationBox3PCF(catalog, ells, edges=numpy.linspace(0, 200, 8+1), BoxSize=1024.)
  File "/dev/shm/local/lib/python3.6/site-packages/nbodykit/algorithms/threeptcf.py", line 252, in __init__
    self.poles = self.run()
  File "/dev/shm/local/lib/python3.6/site-packages/nbodykit/algorithms/threeptcf.py", line 288, in run
    return self._run(pos, w, pos_sec, w_sec, boxsize=boxsize)
  File "/dev/shm/local/lib/python3.6/site-packages/nbodykit/algorithms/threeptcf.py", line 56, in _run
    Ylm_cache = YlmCache(self.attrs['poles'], self.comm)
  File "/dev/shm/local/lib/python3.6/site-packages/nbodykit/algorithms/threeptcf.py", line 453, in __init__
    expr = expr.replace(var[0], 'from_cache(%s, %s)' %var[1:])
  File "/dev/shm/local/lib/python3.6/site-packages/sympy/core/basic.py", line 1459, in replace
    "first argument to replace() must be a "
TypeError: first argument to replace() must be a type, an expression or a callable
Traceback (most recent call last):

Thanks!

**Comment by rainwoodman** [comment]
I think this is supposed to be fixed in #581, in 0.3.11.

I wonder why NERSC didn't get this update though..

Could you do 
```
srun -n 1 python -c 'import nbodykit; print(nbodykit.__version__)'
```

**Comment by rainwoodman** [comment]
I think I figured out why it is not updating. nbodykit on Cori is updated to 0.3.11. If you run your scripts again it should be fixed.
