### ISSUE TITLE
install fails.

### ISSUE THREAD

**Issue by pengastro** [bccp/nbodykit#601]
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: nbodykit[extras] in /Users/wangpeng/nbodykit (0.3.14.dev0)
Requirement already satisfied: numpy in /usr/local/lib/python2.7/site-packages (from nbodykit[extras]) (1.16.4)
Requirement already satisfied: scipy in /Users/wangpeng/Library/Python/2.7/lib/python/site-packages (from nbodykit[extras]) (0.19.0)
Requirement already satisfied: astropy in /usr/local/lib/python2.7/site-packages (from nbodykit[extras]) (2.0.2)
Requirement already satisfied: mpi4py in /usr/local/lib/python2.7/site-packages (from nbodykit[extras]) (3.0.0)
Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages (from nbodykit[extras]) (1.11.0)
Collecting runtests (from nbodykit[extras])
  Using cached https://files.pythonhosted.org/packages/0b/8e/20413579a2e9fe0d9ff59f2c247cac5b3a0fcd765869b10b968a1fdf4714/runtests-0.0.27.tar.gz
Collecting pmesh (from nbodykit[extras])
  Using cached https://files.pythonhosted.org/packages/6a/2c/efd09c4a42bb1da87ec9d2085b52fb7b80ca25464c13e343278d349b4ba3/pmesh-0.1.54.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/80/y46l7yk55mdcyvrm8tp3r9rh0000gn/T/pip-install-f9ilpp/pmesh/setup.py'"'"'; __file__='"'"'/private/var/folders/80/y46l7yk55mdcyvrm8tp3r9rh0000gn/T/pip-install-f9ilpp/pmesh/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/80/y46l7yk55mdcyvrm8tp3r9rh0000gn/T/pip-install-f9ilpp/pmesh/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/80/y46l7yk55mdcyvrm8tp3r9rh0000gn/T/pip-install-f9ilpp/pmesh/setup.py", line 46, in <module>
        from Cython.Build import cythonize
    ImportError: No module named Cython.Build
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by rainwoodman** [comment]
We probably forget to declare a cython dependency. What if you install
cython first?

**Comment by rainwoodman** [comment]
This is a known issue about setuptools cannot specify build type dependency in setup.py. https://github.com/pypa/pip/issues/2381

A known workaround is to manually install the missing dependencies before running pip install -- in this case, when pip complains about cython, then you can do a pip install cython. When it continues to complain about numpy, then you can do a pip install numpy -- till all dependcies are figured out.

(I think you'll need mpi4py, cython, numpy, but you may need more)

It is much easier if you install nbodykit via `conda install -c bccp nbodykit`. Strongly recommend you to use conda, unless your hands are tied (e.g. on a super computing center and need to use their MPI).

**Comment by pengastro** [comment]
Hi,

Thanks for reply.

I do use conda to install nbodykit on Mac.
The previous problem is fixed now, while I meet a other problem:

ld: library not found for -lgfortran




Actually,  fortran on my Mac is well installed, I can use it to compile fortran code.
Do you know is there any way to fix this ?

Cheers
Peng

**Comment by rainwoodman** [comment]
Could you post the command you typed and the full log?

If you install from conda, then there shouldn't be a -lgfortran warning
from ld -- everything should have already been compiled.

The conda recipes can be found on github.com/bccp/conda-channel-bccp. I
usually find it easier to compile nbodykit with anaconda's compilers (
https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html
).

Yu

**Comment by londumas** [comment]
I can confirm the failing pip install:
```
Collecting nbodykit
  Using cached https://files.pythonhosted.org/packages/85/68/6ca93a18da4e957476a9a94518c0e979d4a9989c7217804f94c549d09e77/nbodykit-0.3.13.tar.gz
Requirement already satisfied, skipping upgrade: numpy in <HOME>/.local/lib/python3.7/site-packages (from nbodykit) (1.18.2)
Requirement already satisfied, skipping upgrade: scipy in <HOME>/.local/lib/python3.7/site-packages (from nbodykit) (1.4.1)
Requirement already satisfied, skipping upgrade: astropy in <HOME>/.local/lib/python3.7/site-packages (from nbodykit) (4.0.1.post1)
Requirement already satisfied, skipping upgrade: mpi4py in <HOME>/.local/lib/python3.7/site-packages (from nbodykit) (3.0.3)
Requirement already satisfied, skipping upgrade: six in <HOME>/.local/lib/python3.7/site-packages (from nbodykit) (1.14.0)
Collecting runtests (from nbodykit)
  Using cached https://files.pythonhosted.org/packages/80/bd/873f4a24291747485c3074018566e85a6bb936c576869f61863e94dd45a2/runtests-0.0.28.tar.gz
Collecting pmesh (from nbodykit)
  Using cached https://files.pythonhosted.org/packages/de/51/e2055acc9b1ad1e6f9b1d1c2576ad001cedd7a5cfb4cb58303638902bc41/pmesh-0.1.55.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-424p155y/pmesh/setup.py", line 46, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-424p155y/pmesh/
```

**Comment by rainwoodman** [comment]
Did you try installing cython first as described in https://github.com/bccp/nbodykit/issues/601#issuecomment-535089668?

**Comment by londumas** [comment]
> Did you try installing cython first as described in [#601 (comment)](https://github.com/bccp/nbodykit/issues/601#issuecomment-535089668)?

Indeed this solution works, `python -m pip install cython`, but is not ideal.

**Comment by rainwoodman** [comment]
```conda install -c bccp nbodykit``` should be more streamlined as it avoids running setup.py.
