### ISSUE TITLE
Memory error generating random catalog

### ISSUE THREAD

**Issue by davidcato** [bccp/nbodykit#635]
Hi all,

I'm trying to use the ConvolvedFFTPower on simulated Halo catalog and I was wondering if there is some way to estimate the amount of memory needed for such task. The Halo catalog is around 3GB size and I 'm generating a random catalog 10 times bigger. I have already tried to perform this analyses in a cluster allocating 192 cores with ~2.5 GB of memory by core and I got a memory error. Seems that the error raise when I generate the random catalog:

```
Traceback (most recent call last):
  File "analyses_plc-various.py", line 115, in <module>
    pinoran['nu'] = pinoran.rng.uniform(low=0., high=1.)
  File "/scratch/eggelinea/david.torres/envs/heidelberg/lib/python2.7/site-packages/nbodykit/mpirng.py", line 96, in uniform
    return self._call_rngmethod(sampler, (low, high), itemshape, dtype)
  File "/scratch/eggelinea/david.torres/envs/heidelberg/lib/python2.7/site-packages/nbodykit/mpirng.py", line 111, in _call_rngmethod
    padded_r, running_args = self._prepare_args_and_result(args, itemshape, dtype)
  File "/scratch/eggelinea/david.torres/envs/heidelberg/lib/python2.7/site-packages/nbodykit/mpirng.py", line 50, in _prepare_args_and_result
    r = numpy.zeros((self.size,) + tuple(itemshape), dtype=dtype)
MemoryError
```

I'm using version 0.3.14 with python2.7. I have also modify the class BinaryCatalog to read binary catalog a row-major format.

Regards,

David Camarena

**Comment by rainwoodman** [comment]
Hi David,

Could you share your job scripts allocating 192 cores and how you started your python script?
Did you compile nbodykit (actually, mpi4py, bigfile and pfft-python)?

Could you confirm that you are actually using 192 cores by doing:

print(pinoran.comm.rank)

in your script?

What is your setting of OMP_NUM_THREADS. When using 1 MPI process per core, usually we set OMP_NUM_THREADS=1 to avoid core-oversubscription which drastically degrades the performance and increase memory consumption to some extent.

PS: Unlikely be causing this, but Python 2.7 has reached end-of-life earlier this year, and we have started using Py3 only features in nbodykit.

**Comment by davidcato** [comment]
Thanks for the reply. Here is the job script (I didn't set OMP_NUM_THREADS):
```
#!/bin/bash
#SBATCH --nodes=8                     
#SBATCH --ntasks=192                  	
#SBATCH -p cpu_small                   
#SBATCH -J PLCANALYSES	              
#SBATCH --time=1:45:00                 
#SBATCH --exclusive                   

echo $SLURM_JOB_NODELIST
nodeset -e $SLURM_JOB_NODELIST

echo $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module load anaconda2/2018.12
source /scratch/app/anaconda2/2018.12/etc/profile.d/conda.sh
conda activate /scratch/eggelinea/david.torres/envs/heidelberg

srun -n $SLURM_NTASKS python analyses_plc-various.py
```
Here the headlines python script:
```
from nbodykit.base import mesh
from nbodykit.lab import *
from nbodykit.source import catalog
from nbodykit import setup_logging, style
import numpy as np
import os
import dask.array as da

setup_logging()
```
I have install nbodykit and all its dependency using anaconda `conda install -c bccp nbodykit`.

I just added `print(pinoran.comm.rank)` in the python script and resubmit my job properly setting OMP_NUM_THREADS=1 but it could take a while to get the output.

**Comment by davidcato** [comment]
Hi,

I rerun my job setting OMP_NUM_THREADS=1and I'm still having memory error. Surprisingly `print(pinoran.comm.rank)` didn't print anything but `print(comm.rank)` prints ntasks times zero. Also, all the logging messages are printed ntasks times.

**Comment by rainwoodman** [comment]
Hi David,

if print(comm.rank) you only get 0s, it means the different processes are
not properly talking to each other as members of MPI.
I see that you are running srun. I suspect you'll need to manually
recompile pfft-python, mpsort and mpi4py for the site's MPI installation
with

conda uninstall --force mpich
pip install -U --force-reinstall pfft-python mpsort mpi4py

These steps are to make sure these packages are compiled with the MPI
installed on the system/site that is compatible with srun.
The one we download from conda (a simple mpich) does not.

This is also one of the reasons on NERSC (uses CrayMPI) we provide a
separate conda environment for users (the other reason is to deploy the
application faster when running on >1000 ranks).



- Yu
