### ISSUE TITLE
Attempting to use an MPI routine before initializing MPICH

### ISSUE THREAD

**Issue by dforero0896** [bccp/nbodykit#636]
**Describe the bug**
When running the MPI example (https://nbodykit.readthedocs.io/en/latest/results/parallel.html#parallel-computation) on a newly built nbodykit environment I obtain the error ```Attempting to use an MPI routine before initializing MPICH```
and the code exits.

**Steps To Reproduce**
Build nbodykit with conda, follow steps for example in here https://nbodykit.readthedocs.io/en/latest/results/parallel.html#parallel-computation

**Actual behaviour**
Error  ```Attempting to use an MPI routine before initializing MPICH``` and exit.

**Expected behaviour**
It should work

**Version**
Find the version of nbodykit by running
```
<module 'nbodykit' from '/home/astro/dforero/.conda/envs/nbk-env/lib/python3.6/site-packages/nbodykit/__init__.py'> 0.3.14
```

**Comment by rainwoodman** [comment]
Usually this indicates you have a conflicting version of MPI either in your system or installed in conda.

Is this a Mac or a Linux cluster?

Would you shared the results of the following commands:

(**make sure your are in nbk-env**)
```
which mpirun
```
```
mpirun --version
```
```
conda list  
```
```
mpirun -n 4 python -c `from mpi4py import MPI; print(MPI.COMM_WORLD.size)`
```

It may be worthwhile that you check your .profile / .bashrc or similar files if you have lines that enable certain MPI environments in ways that may override Anaconda's MPI. 

If this is a cluster, usually you can find in the documentation of the cluster instructions on running and compiling MPI applications with different versions of MPI.

**Comment by dforero0896** [comment]
Hi, thanks for your answer. It is a Linux cluster.
In nbk-env:
```
which mpirun
~/.conda/envs/nbk-env/bin/mpirun
```
```
mpirun --version
HYDRA build details:
    Version:                                 3.3.2
    Release Date:                            Tue Nov 12 21:23:16 CST 2019
    CC:                              x86_64-conda_cos6-linux-gnu-cc -I/home/astro/dforero/.conda/envs/nbk-env/include -I/home/astro/dforero/.conda/envs/nbk-env/include -L/home/astro/dforero/.conda/envs/nbk-env/lib -Wl,-rpath,/home/astro/dforero/.conda/envs/nbk-env/lib 
    CXX:                             x86_64-conda_cos6-linux-gnu-c++ -I/home/astro/dforero/.conda/envs/nbk-env/include -I/home/astro/dforero/.conda/envs/nbk-env/include -L/home/astro/dforero/.conda/envs/nbk-env/lib -Wl,-rpath,/home/astro/dforero/.conda/envs/nbk-env/lib 
    F77:                             x86_64-conda_cos6-linux-gnu-gfortran -I/home/astro/dforero/.conda/envs/nbk-env/include -L/home/astro/dforero/.conda/envs/nbk-env/lib -Wl,-rpath,/home/astro/dforero/.conda/envs/nbk-env/lib 
    F90:                             x86_64-conda_cos6-linux-gnu-gfortran -I/home/astro/dforero/.conda/envs/nbk-env/include -L/home/astro/dforero/.conda/envs/nbk-env/lib -Wl,-rpath,/home/astro/dforero/.conda/envs/nbk-env/lib 
    Configure options:                       '--disable-option-checking' '--prefix=/home/astro/dforero/.conda/envs/nbk-env' '--disable-dependency-tracking' '--enable-cxx' '--enable-fortran' '--disable-wrapper-rpath' 'MPICHLIB_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/astro/dforero/.conda/envs/nbk-env/include -fdebug-prefix-map=/tmp/build/80754af9/mpich-mpi_1575396103289/work=/usr/local/src/conda/mpich-3.3.2 -fdebug-prefix-map=/home/astro/dforero/.conda/envs/nbk-env=/usr/local/src/conda-prefix' 'MPICHLIB_CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -I/home/astro/dforero/.conda/envs/nbk-env/include' 'MPICHLIB_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/astro/dforero/.conda/envs/nbk-env/include -fdebug-prefix-map=/tmp/build/80754af9/mpich-mpi_1575396103289/work=/usr/local/src/conda/mpich-3.3.2 -fdebug-prefix-map=/home/astro/dforero/.conda/envs/nbk-env=/usr/local/src/conda-prefix' 'MPICHLIB_FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/astro/dforero/.conda/envs/nbk-env/include -fdebug-prefix-map=/tmp/build/80754af9/mpich-mpi_1575396103289/work=/usr/local/src/conda/mpich-3.3.2 -fdebug-prefix-map=/home/astro/dforero/.conda/envs/nbk-env=/usr/local/src/conda-prefix' 'MPICHLIB_FCFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/astro/dforero/.conda/envs/nbk-env/include -fdebug-prefix-map=/tmp/build/80754af9/mpich-mpi_1575396103289/work=/usr/local/src/conda/mpich-3.3.2 -fdebug-prefix-map=/home/astro/dforero/.conda/envs/nbk-env=/usr/local/src/conda-prefix' 'CC=x86_64-conda_cos6-linux-gnu-cc' 'CFLAGS=-I/home/astro/dforero/.conda/envs/nbk-env/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/astro/dforero/.conda/envs/nbk-env/include -fdebug-prefix-map=/tmp/build/80754af9/mpich-mpi_1575396103289/work=/usr/local/src/conda/mpich-3.3.2 -fdebug-prefix-map=/home/astro/dforero/.conda/envs/nbk-env=/usr/local/src/conda-prefix -O2' 'LDFLAGS=-L/home/astro/dforero/.conda/envs/nbk-env/lib -Wl,-rpath,/home/astro/dforero/.conda/envs/nbk-env/lib' 'CPPFLAGS=-I/home/astro/dforero/.conda/envs/nbk-env/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -I/home/astro/dforero/.conda/envs/nbk-env/include -I/tmp/build/80754af9/mpich-mpi_1575396103289/work/src/mpl/include -I/tmp/build/80754af9/mpich-mpi_1575396103289/work/src/mpl/include -I/tmp/build/80754af9/mpich-mpi_1575396103289/work/src/openpa/src -I/tmp/build/80754af9/mpich-mpi_1575396103289/work/src/openpa/src -D_REENTRANT -I/tmp/build/80754af9/mpich-mpi_1575396103289/work/src/mpi/romio/include' 'CPP=/home/astro/dforero/.conda/envs/nbk-env/bin/x86_64-conda_cos6-linux-gnu-cpp' 'CXX=x86_64-conda_cos6-linux-gnu-c++' 'CXXFLAGS=-I/home/astro/dforero/.conda/envs/nbk-env/include -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/astro/dforero/.conda/envs/nbk-env/include -fdebug-prefix-map=/tmp/build/80754af9/mpich-mpi_1575396103289/work=/usr/local/src/conda/mpich-3.3.2 -fdebug-prefix-map=/home/astro/dforero/.conda/envs/nbk-env=/usr/local/src/conda-prefix -O2' 'FC=x86_64-conda_cos6-linux-gnu-gfortran' 'FCFLAGS=-I/home/astro/dforero/.conda/envs/nbk-env/include -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/astro/dforero/.conda/envs/nbk-env/include -fdebug-prefix-map=/tmp/build/80754af9/mpich-mpi_1575396103289/work=/usr/local/src/conda/mpich-3.3.2 -fdebug-prefix-map=/home/astro/dforero/.conda/envs/nbk-env=/usr/local/src/conda-prefix -O2' 'FFLAGS=-I/home/astro/dforero/.conda/envs/nbk-env/include -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/astro/dforero/.conda/envs/nbk-env/include -fdebug-prefix-map=/tmp/build/80754af9/mpich-mpi_1575396103289/work=/usr/local/src/conda/mpich-3.3.2 -fdebug-prefix-map=/home/astro/dforero/.conda/envs/nbk-env=/usr/local/src/conda-prefix -O2' '--cache-file=/dev/null' '--srcdir=.' 'LIBS=' 'MPLLIBNAME=mpl'
    Process Manager:                         pmi
    Launchers available:                     ssh rsh fork slurm ll lsf sge manual persist
    Topology libraries available:            hwloc
    Resource management kernels available:   user slurm ll lsf sge pbs cobalt
    Checkpointing libraries available:       
    Demux engines available:                 poll select

```
```
conda list  
# packages in environment at /home/astro/dforero/.conda/envs/nbk-env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
astropy                   4.0.1.post1      py36h7b6447c_1  
atomicwrites              1.4.0                      py_0  
attrs                     19.3.0                     py_0  
beautifulsoup4            4.9.1                    py36_0  
bigfile                   0.1.49           py36h7ad7176_7    bccp
blas                      1.0                         mkl  
bokeh                     2.1.1                    py36_0  
brotlipy                  0.7.0           py36h7b6447c_1000  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.6.20            hecda079_0    conda-forge
cachey                    0.2.1                    py36_0    bccp
certifi                   2020.6.20        py36h9f0ad1d_0    conda-forge
cffi                      1.14.1           py36he30daa8_0  
chardet                   3.0.4                 py36_1003  
classylss                 0.2.9            py36h81ec5f0_7    bccp
click                     7.1.2                      py_0  
cloudpickle               1.5.0                      py_0  
contextvars               2.4                        py_0  
corrfunc                  2.3.0           py36h7ad7176_10    bccp
coverage                  5.2.1            py36h7b6447c_0  
cryptography              2.9.2            py36h1ba5d50_0  
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.21          py36he6710b0_0  
cytoolz                   0.10.1           py36h7b6447c_0  
dask                      2.20.0                     py_0  
dask-core                 2.20.0                     py_0  
distributed               2.20.0                   py36_0  
fastcache                 1.1.0            py36h7b6447c_0  
fitsio                    1.1.2            py36h7ad7176_5    bccp
freetype                  2.10.2               h5ab3b9f_0  
fsspec                    0.8.0                      py_0  
future                    0.18.2                   py36_1  
gmp                       6.1.2                h6c8ec71_1  
gmpy2                     2.0.8            py36h10f8cd9_2  
gsl                       2.4                  h14c3975_4  
h5py                      2.10.0           py36hd6299e0_1  
halotools                 0.7              py36h05e7f39_5    bccp
hdf5                      1.10.6               hb1b8bf9_0  
heapdict                  1.0.1                      py_0  
idna                      2.10                       py_0  
immutables                0.14             py36h7b6447c_0  
importlib-metadata        1.7.0                    py36_0  
importlib_metadata        1.7.0                         0  
intel-openmp              2020.1                      217  
jinja2                    2.11.2                     py_0  
jpeg                      9b                   h024ee3a_2  
kdcount                   0.3.29           py36h7ad7176_5    bccp
kiwisolver                1.2.0            py36hdb11119_0    conda-forge
krb5                      1.18.2               h173b8e3_0  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libcurl                   7.71.1               h20c2e04_1  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
locket                    0.2.0                    py36_1  
lz4-c                     1.9.2                he6710b0_1  
markupsafe                1.1.1            py36h7b6447c_0  
matplotlib                3.3.1                         1    conda-forge
matplotlib-base           3.3.1            py36h5ffbc53_1    conda-forge
mcfit                     0.0.17           py36hc873e9d_1    bccp
mkl                       2020.1                      217  
mkl-service               2.3.0            py36he904b0f_0  
mkl_fft                   1.1.0            py36h23d657b_0  
mkl_random                1.1.1            py36h0573a6f_0  
more-itertools            8.4.0                      py_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpi                       1.0                       mpich  
mpi4py                    3.0.3            py36h028fd6f_0  
mpich                     3.3.2                hc856adb_0  
mpmath                    1.1.0                    py36_0  
mpsort                    0.1.17           py36h314f505_9    bccp
msgpack-python            1.0.0            py36hfd86e86_1  
nbodykit                  0.3.14           py36hc873e9d_6    bccp
ncurses                   6.2                  he6710b0_1  
numexpr                   2.7.1            py36h423224d_0  
numpy                     1.19.1           py36hbc911f0_0  
numpy-base                1.19.1           py36hfa32c7d_0  
olefile                   0.46                       py_0  
openssl                   1.1.1g               h516909a_1    conda-forge
packaging                 20.4                       py_0  
pandas                    1.1.0            py36he6710b0_0  
partd                     1.1.0                      py_0  
pfft-python               0.1.21          py36h314f505_10    bccp
pillow                    7.2.0            py36hb39fc2d_0  
pip                       20.2.2                   py36_0  
pluggy                    0.13.1                   py36_0  
pmesh                     0.1.55           py36h7ad7176_5    bccp
psutil                    5.7.0            py36h7b6447c_0  
py                        1.9.0                      py_0  
pycparser                 2.20                       py_2  
pyopenssl                 19.1.0                     py_1  
pyparsing                 2.4.7                      py_0  
pysocks                   1.7.1                    py36_0  
pytest                    5.0.1                    py36_0  
python                    3.6.10               h7579374_2  
python-dateutil           2.8.1                      py_0  
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2020.1                     py_0  
pyyaml                    5.3.1            py36h7b6447c_1  
readline                  8.0                  h7b6447c_0  
requests                  2.24.0                     py_0  
runtests                  0.0.28                   py36_2    bccp
scipy                     1.5.0            py36h0b6359f_0  
setuptools                49.6.0                   py36_0  
six                       1.15.0                     py_0  
sortedcontainers          2.2.2                      py_0  
soupsieve                 2.0.1                      py_0  
sqlite                    3.33.0               h62c20be_0  
sympy                     1.5.1                    py36_0  
tblib                     1.7.0                      py_0  
tk                        8.6.10               hbc83047_0  
toolz                     0.10.0                     py_0  
tornado                   6.0.4            py36h7b6447c_1  
typing_extensions         3.7.4.2                    py_0  
urllib3                   1.25.10                    py_0  
wcwidth                   0.2.5                      py_0  
wheel                     0.34.2                   py36_0  
wurlitzer                 2.0.1                    py36_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
zict                      2.0.0                      py_0  
zipp                      3.1.0                      py_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0  

```
```
mpirun -n 4 python -c `from mpi4py import MPI; print(MPI.COMM_WORLD.size)
4
4
4
4
```
The weird issue is that I usually have no problem at all running MPI-enabled codes, this is the first time I get such a message. When I run the code locally (Ubuntu 18) I have no problems at all even if I don't `mpirun python mycode.py` but just `python mycode.py`.

As for my .bashrc and .bash_profile, what do you suggest I look for? I just `module load` some package but nothing weird.

Thanks

**Comment by rainwoodman** [comment]
Thanks for the tests. So far all of these looked OK. We only have one
version of mpich and it is the one that's shipped from conda. The conda
environment is very much the same as your local system.

The fact that some MPI codes work on the cluster, but nbodykit doesn't,
also points to nbodykit being compiled with an incompatible MPI. (as the
preference of your cluster).

For bash_profile, check if there are lines that sets LD_LIBRARY_PATH or
LD_PRELOAD, or similar manipulations of paths. module command may also do
that.
If there is a cluster version of MPI that is higher in priority than the
one came from conda, then this can happen.

As you are running on a cluster, eventually you may have to recompile
mpi4py / pfft-python / bigfile / mpsort for the cluster using the cluster's
preferred MPI.

The one shipped by conda, even after we get it "working", is unlikely going
to support jobs that use multiple nodes.


Also, I recalled that MPI.COMM_WORLD.size may not always require MPI
initialization. What about running

mpirun -n 4 python -c `from mpi4py import MPI;
MPI.COMM_WORLD.barrier(); print(MPI.COMM_WORLD.size)`

(in the place where you would have run your nbodykit script).

I would expect this to fail. (at the barrier())

- Yu

**Comment by dforero0896** [comment]
Hi
My .bashrc does modify LD_LIBRARY_PATH but seems unrelated (adds Multinest lib).
As for the test it looks ok , I get again 
```
4
4
4
4
```
I believe mpi4py is initialized upon importing MPI with `from mpi4py import MPI` so it is not surprising that it still works.
I regularly use a conda-built MPI to launch multi-node jobs in the cluster so I would expect if we get nbodykit working it could work on multiple nodes.

Cheers,
DF

**Comment by rainwoodman** [comment]
This is really strange. Basically this is saying whatever triggered the MPICH uninitialized error, has linked to a different version of MPI than mpi4py...

Is it possible to locate which python line triggered the initialization error? Perhaps running python with '-v'?

Another possible avenue (may fix this without getting to the root cause), is to override the version of MPI-using modules with a local build. `pip install pfft-python mpsort bigfile`, or something like this (perhaps need a -U)

**Comment by dforero0896** [comment]
Hi, 
I couldn't see which line triggered the error with -v (too much output, don't know what to look for). However i managed to dodge the error until I had to create the density mesh for the power spectrum so I think that is the line. 
When I try to local build those packages I just get a "requirement already satisfied" or so message for all of them.

**Comment by rainwoodman** [comment]
Thanks for the information.

Creating the density mesh does require doing some MPI communications. It
may also trigger the FFT, which suggests pfft-python may be the culprit.
Let's run a small test to make sure it works:

mpirun -n 4 python -c 'from pfft.tests import test_pfft;
test_pfft.test_2d_on_2d_r2c(4)'

About the requirement satisfied error: Perhaps there are flags to force a
reinstall, like -f or -U (hidden in pip install --help)

Yu

**Comment by dforero0896** [comment]
Hi,
That sounds about right, that test does give me the same error.
```
mpirun -n 4 python -c 'from pfft.tests import test_pfft;
test_pfft.test_2d_on_2d_r2c(4)'

Attempting to use an MPI routine before initializing MPICH  
Attempting to use an MPI routine before initializing MPICH  
Attempting to use an MPI routine before initializing MPICH  
Attempting to use an MPI routine before initializing MPICH  
```
However, using --force-reinstall with pip packages are reinstalled but  still get the same error. I also upgraded with conda `conda update -c bccp pfft-python` .

Cheers

**Comment by rainwoodman** [comment]
Great!

What about running `ldd` on some of the 'so' files from pfft and from
mpi4py, then compare the difference?

You can find the pfft 'so' object under a subdirectory
$CONDA_PREFIX/lib/python-?.?/site-packages/pfft*.so
and similarly for mpi4py.

At this point, they'd better disagree...

- Yu

**Comment by dforero0896** [comment]
Hi, 

I didn't find the directory you suggested (changing `python-?.?` to `python3.6`). Using `find` however I found one `.so`: `core.cpython-36m-x86_64-linux-gnu.so`. 
```
(nbk-env) dforero@lesta01:~$ ldd /home/astro/dforero/.conda/envs/nbk-env/lib/python3.6/site-packages/pfft/core.cpython-36m-x86_64-linux-gnu.so
        linux-vdso.so.1 =>  (0x00007ffcb60e5000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f35ac438000)
        libmpi.so.12 => /home/astro/dforero/.conda/envs/nbk-env/lib/libmpi.so.12 (0x00007f35ac113000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f35abf0b000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f35abcef000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f35ab922000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f35acae0000)
        libgfortran.so.4 => /home/astro/dforero/.conda/envs/nbk-env/lib/./libgfortran.so.4 (0x00007f35acbae000)
        libgomp.so.1 => /home/astro/dforero/.conda/envs/nbk-env/lib/./libgomp.so.1 (0x00007f35acb80000)
        libgcc_s.so.1 => /home/astro/dforero/.conda/envs/nbk-env/lib/./libgcc_s.so.1 (0x00007f35acb6c000)
        libquadmath.so.0 => /home/astro/dforero/.conda/envs/nbk-env/lib/./libquadmath.so.0 (0x00007f35acb32000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f35ab71e000)
```
When I do the same with `mpi4py` I find 6 `.so` :
```
/home/astro/dforero/.conda/envs/nbk-env/lib/python3.6/site-packages/mpi4py/MPI.cpython-36m-x86_64-linux-gnu.so
/home/astro/dforero/.conda/envs/nbk-env/lib/python3.6/site-packages/mpi4py/lib-pmpi/libvt-hyb.so
/home/astro/dforero/.conda/envs/nbk-env/lib/python3.6/site-packages/mpi4py/lib-pmpi/libvt.so
/home/astro/dforero/.conda/envs/nbk-env/lib/python3.6/site-packages/mpi4py/lib-pmpi/libmpe.so
/home/astro/dforero/.conda/envs/nbk-env/lib/python3.6/site-packages/mpi4py/lib-pmpi/libvt-mpi.so
/home/astro/dforero/.conda/envs/nbk-env/lib/python3.6/site-packages/mpi4py/dl.cpython-36m-x86_64-linux-gnu.so
```
When I `ldd` the firs one I get

```
(nbk-env) dforero@lesta01:~$ ldd /home/astro/dforero/.conda/envs/nbk-env/lib/python3.6/site-packages/mpi4py/MPI.cpython-36m-x86_64-linux-gnu.so
        linux-vdso.so.1 =>  (0x00007ffcb0dba000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fce438cc000)
        libmpich.so.3 => /home/epfl/dforero/.conda/envs/gravitational_lens_ml/lib/libmpich.so.3 (0x00007fce434eb000)
        libopa.so.1 => /home/epfl/dforero/.conda/envs/gravitational_lens_ml/lib/libopa.so.1 (0x00007fce432ea000)
        libmpl.so.1 => /home/epfl/dforero/.conda/envs/gravitational_lens_ml/lib/libmpl.so.1 (0x00007fce430e6000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fce42ede000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fce42cc2000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fce428f5000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fce43ad0000)
```
Which is interesting since it seems to be linking `mpich` from other of my environments. Maybe that is the issue?  How do I fix this?

Cheers

**Comment by rainwoodman** [comment]
You are looking at the correct MPI*.so file. All objects in a conda environment should link to the resolve to the libraries in the same conda environment. So this is indicating something is wrong with the conda environment.

I have never run into a situation like this before. Perhaps start with a new conda environment?

Here is a possible way to salvage your current nbkit environment:
```
conda clean --all
conda remove --force mpich mpi4py
conda install mpich mpi4py
```
the conda clean line may be important, as if there are corrupted conda packages in the cache, it will get rid of it. 

One the side, could you activate gravitational_lens_ml, and post the result of conda list mpich mpi4py?
I wonder if you are using a broken mpi4py build (esp if it is not coming from anaconda/default)

**Comment by dforero0896** [comment]
Hello, 
`conda clean --all` appears to have fixed the issue, however I removed and re-built the environment as in https://nbodykit.readthedocs.io/en/latest/getting-started/install.html .
However, I now face another issue, I put the output of the example here just in case there is a quick fix, otherwise I can open other issue or dig around a bit more
```
(nbk-env) dforero@lesta01:~/scratch/projects/baosystematics/src/powspec$ python example.py 
[ 000003.68 ]   0: 09-08 01:26  LogNormalCatalog INFO     Growth Rate is 0.770123
[ 000003.68 ]   0: 09-08 01:26  LogNormalCatalog INFO     Generating whitenoise
[ 000003.72 ]   0: 09-08 01:26  LogNormalCatalog INFO     Write noise generated
[ 000003.73 ]   0: 09-08 01:26  LogNormalCatalog INFO     Displacement computed in fourier space
[ 000003.73 ]   0: 09-08 01:26  LogNormalCatalog INFO     Overdensity computed in configuration space: std = 0.05068950434859907
[ 000003.73 ]   0: 09-08 01:26  LogNormalCatalog INFO     Displacement computed in configuration space: std = [1.9101123141675138, 1.861070837309468, 1.9480986348663696]
[ 000003.74 ]   0: 09-08 01:26  LogNormalCatalog INFO     gaussian field is generated
[ 000003.74 ]   0: 09-08 01:26  LogNormalCatalog INFO     Lognormal transformation done
[ 000003.74 ]   0: 09-08 01:26  LogNormalCatalog INFO     Poisson sampling done, total number of objects is 825
[ 000003.74 ]   0: 09-08 01:26  LogNormalCatalog INFO     catalog produced. Assigning in cell shift.
[ 000003.74 ]   0: 09-08 01:26  LogNormalCatalog INFO     sorting done
[ 000003.74 ]   0: 09-08 01:26  LogNormalCatalog INFO     catalog shifted.
[ 000003.74 ]   0: 09-08 01:26  LogNormalCatalog INFO     poisson sampling is generated
[ 000003.76 ]   0: 09-08 01:26  CatalogMesh     INFO     Chunk 0 ~ 4194304 / 825 
Traceback (most recent call last):
  File "example.py", line 17, in <module>
    result = FFTPower(source, mode='2d', poles=[0,2,4], los=[0,0,1])
  File "/home/astro/dforero/.conda/envs/nbk-env/lib/python3.6/site-packages/nbodykit/algorithms/fftpower.py", line 224, in __init__
    self.power, self.poles = self.run()
 File "/home/astro/dforero/.conda/envs/nbk-env/lib/python3.6/site-packages/nbodykit/algorithms/fftpower.py", line 281, in run
    y3d, attrs = self._compute_3d_power(self.first, self.second)
  File "/home/astro/dforero/.conda/envs/nbk-env/lib/python3.6/site-packages/nbodykit/algorithms/fftpower.py", line 105, in _compute_3d_power
    c1 = first.compute(mode='complex', Nmesh=self.attrs['Nmesh'])
  File "/home/astro/dforero/.conda/envs/nbk-env/lib/python3.6/site-packages/nbodykit/base/mesh.py", line 250, in compute
    return self._paint_XXX(mode=mode, Nmesh=Nmesh)
  File "/home/astro/dforero/.conda/envs/nbk-env/lib/python3.6/site-packages/nbodykit/base/mesh.py", line 289, in _paint_XXX
    var = self.to_field(mode=actions[0][0])
  File "/home/astro/dforero/.conda/envs/nbk-env/lib/python3.6/site-packages/nbodykit/base/mesh.py", line 235, in to_field
    real = self.to_real_field()
  File "/home/astro/dforero/.conda/envs/nbk-env/lib/python3.6/site-packages/nbodykit/source/mesh/catalog.py", line 311, in to_real_field
    Nlocal1, Wlocal1, W2local1 = dochunk(s)
  File "/home/astro/dforero/.conda/envs/nbk-env/lib/python3.6/site-packages/nbodykit/source/mesh/catalog.py", line 276, in dochunk
    newlengths = pm.comm.allgather(lay.newlength)
AttributeError: 'Layout' object has no attribute 'newlength'
```
I updated the environment in case it was the issue with `conda update -c bccp --all`.

Thanks for all your help.

**Comment by rainwoodman** [comment]
Glad that part is fixed. the newlength issue is fixed
https://github.com/bccp/nbodykit/pull/640.

I am pushing a new version soon (hopefully today).

For a temporary workaround, you can run `conda install -c bccp
pmesh==0.1.55`

or

pip install https://github.com/bccp/nbodykit/archive/master.zip

Yu
